export const INCREMENT = 'INCREMENT'

export const OPEN_CLOSE_ITEM = 'OPEN_CLOSE_ITEM'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'

export const SET_COMMENT_TEXT = 'SET_COMMENT_TEXT'

export const SET_COMMENT_NAME = 'SET_COMMENT_NAME'

export const ADD_COMMENT = 'ADD_COMMENT'

export const ADD_COMMENT_TO_ARTICLE = 'ADD_COMMENT_TO_ARTICLE'

export const CLEAR_SUBMITTING_COMMENT = 'CLEAR_SUBMITTING_COMMENT'
