export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECTED_ARTICLES_CHANGED = 'SELECTED_ARTICLES_CHANGED'

export const DATE_FILTER_CHANGED = 'DATE_FILTER_CHANGED'
