export const INCREMENT = 'INCREMENT'
export const SELECT_FILTER_CHANGED = 'SELECTED_FILTER_CHANGED'
export const DATE_RANGE_CHANGED = 'DATE_RANGE_CHANGED'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
